apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: test
  labels: 
    app: test
spec: 
  selector:
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: caioaugusto/test